- name: Ensure VM's are configured
  hosts: all
  become: true

  roles:
    - system
    - docker

- name: Ensure Reverb has gpu and plex mounts configured
  hosts: docker
  become: true

  roles:
    - gpu
    - plex