- name: Wait for the hosts to become reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH to be available
      ansible.builtin.wait_for_connection:
        timeout: 300  # seconds
        sleep: 5      # check every 5 seconds

- name: Ensure all hosts are configured
  hosts: all
  become: true

  roles:
    - system
    - docker

- name: Ensure Reverb has gpu and plex mounts configured
  hosts: docker
  become: true

  roles:
    - gpu
    - plex

- name: Ensure Docker Swarm hosts have cephfs mounted
  hosts: docker-swarm
  become: true

  roles:
    - docker-swarm

- name: Ensure Reverb has Portainer agent configured
  hosts: reverb
  become: true

  tasks:
    - name: Configure Portainer agent
      include_tasks: ./roles/docker/tasks/portainer-agent.yaml

- name: Ensure Deora-1 has Docker Swarm configured
  hosts: deora-1
  become: true

  tasks:
    - name: Configure Portainer Swarm agent
      include_tasks: ./roles/docker-swarm/tasks/docker-swarm-init.yaml

- name: Ensure Deora-2 has Docker Swarm configured
  hosts: deora-2
  become: true

  tasks:
    - name: Configure Portainer Swarm agent
      include_tasks: ./roles/docker-swarm/tasks/docker-swarm-join.yaml