- name: Install NFS packages
  package:
    name:
      - nfs-common
    state: latest

- name: Create directories
  file:
    path: /mnt/cephfs
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Modify fstab
  blockinfile:
    path: /etc/fstab
    block: |
      10.27.1.20:6789,10.27.1.30:6789/ /mnt/ceph ceph name=admin,secret={{ ceph_secret }}
    insertafter: EOF

- name: Ensure NFS shares are mounted
  command: mount -a