- name: Initialize Docker Swarm
  shell: "docker swarm init --advertise-addr {{ ansible_host }}"
  register: swarm_init_result
  failed_when: "'This node is already part of a swarm' not in swarm_init_result.stderr and swarm_init_result.rc != 0"

- name: Get Swarm Join Token
  shell: "docker swarm join-token -q worker"
  register: swarm_token
  when: "'This node is already part of a swarm' not in swarm_init_result.stderr"

- name: Set fact for join command
  set_fact:
    swarm_join_cmd: "docker swarm join --token {{ swarm_token.stdout }} {{ ansible_host }}:2377"
  when: swarm_token is defined

- name: Start Portainer Swarm agent
  shell: |
    docker network create \
    --driver overlay \
      portainer_agent_network

    docker service create \
      --name portainer_agent \
      --network portainer_agent_network \
      -p 9001:9001/tcp \
      --mode global \
      --constraint 'node.platform.os == linux' \
      --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
      --mount type=bind,src=//var/lib/docker/volumes,dst=/var/lib/docker/volumes \
      --mount type=bind,src=//,dst=/host \
      portainer/agent:2.27.6