- name: Install NFS packages
  package:
    name:
      - nfs-common
    state: latest

- name: Create directories
  file:
    path: /mnt/plex-fast
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Modify fstab
  blockinfile:
    path: /etc/fstab
    block: |
      10.27.100.1:/mnt/sweeper/plex /mnt/plex-fast nfs defaults  0 0
    insertafter: EOF

- name: Ensure NFS shares are mounted
  command: mount -a