# - name: Add Cloudflare's official GPG key
#   apt_key:
#     url: https://pkg.cloudflare.com/cloudflare-main.gpg
#     state: present

# - name: Add Cloudflare repository
#   apt_repository:
#     repo: deb https://pkg.cloudflare.com/cloudflared {{ ansible_lsb.codename }} main
#     state: present

# - name: Update packages
#   apt:
#     update_cache: true
#     upgrade: true

# - name: Install cloudflared packages
#   package:
#     name:
#       - cloudflared
#     state: latest

- name: Download cloudflared
  get_url:
    url: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64"
    dest: /usr/local/bin/cloudflared
    mode: '0755'

- name: Create a cloudflared service directory.
  shell: |
    mkdir -p /etc/cloudflared/

- name: Create the config file for cloudflared and define the ingress rules for the tunnel.
  copy:
    dest: "/etc/cloudflared/config.yml"
    content: |
      tunnel: "9a990ab8-d203-4eec-9068-e596bb707ea9"
      credentials-file: /etc/cloudflared/cert.json
      loglevel: info
      ingress:
        - hostname: "ssh_app.{{ zone }}"
          service: ssh://localhost:22
        - service: http_status:404

- name: Create the tunnel credentials file for cloudflared.
  copy:
    dest: "/etc/cloudflared/cert.json"
    content: |
      {
        "AccountTag"   : "3166e407ad89d7bb1d1c11ba4b0c935c",
        "TunnelID"     : "9a990ab8-d203-4eec-9068-e596bb707ea9",
        "TunnelName"   : "Smith Labs",
        "TunnelSecret" : "eyJhIjoiMzE2NmU0MDdhZDg5ZDdiYjFkMWMxMWJhNGIwYzkzNWMiLCJ0IjoiOWE5OTBhYjgtZDIwMy00ZWVjLTkwNjgtZTU5NmJiNzA3ZWE5IiwicyI6Ik16ZGhOamRtTTJFdE5HUTNOeTAwTWpWaExUZ3laREl0TnpCaE5tUmlZelEzTTJWbSJ9"
      }

- name: Install the tunnel as a systemd service.
  shell: |
    cloudflared service install

- name: Start cloudflared as service
  systemd:
    name: cloudflared
    enabled: yes
    state: started